/* GENERATED by tools/build-option-shapes.mjs — do not edit by hand.
 *
 * One entry per shape the curriculum names. `points` is the ring TRACED OFF THE
 * ARTWORK, normalised so -1..1 spans the longer side of the image's trimmed box —
 * which means the ring and the texture describe the same rectangle, and the engine can
 * lay one over the other with a single drawImage.
 *
 * `sides`, `convex` and `regular` are measured from that ring, not declared, and the
 * build fails if any of them disagrees with what the curriculum calls the shape. So the
 * number a learner counts on screen is the number the game is checking.
 */
export const optionShapes = {
  "regularTriangle": {
    "image": "assets/option-shape/regularTriangle.webp",
    "sides": 3,
    "regular": true,
    "convex": true,
    "aspect": 1.16922,
    "points": [
      {
        "x": 0.00245,
        "y": -0.85527
      },
      {
        "x": 0.99836,
        "y": 0.852
      },
      {
        "x": -1,
        "y": 0.852
      }
    ]
  },
  "regularQuadrilateral": {
    "image": "assets/option-shape/regularQuadrilateral.webp",
    "sides": 4,
    "regular": true,
    "convex": true,
    "aspect": 0.99894,
    "points": [
      {
        "x": 0.99045,
        "y": -0.99151
      },
      {
        "x": 0.99045,
        "y": 0.97771
      },
      {
        "x": -0.99682,
        "y": 0.98726
      },
      {
        "x": -0.99257,
        "y": -0.98938
      }
    ]
  },
  "regularPentagon": {
    "image": "assets/option-shape/regularPentagon.webp",
    "sides": 5,
    "regular": true,
    "convex": true,
    "aspect": 1.04348,
    "points": [
      {
        "x": -0.00174,
        "y": -0.95833
      },
      {
        "x": 0.99826,
        "y": -0.21007
      },
      {
        "x": 0.57986,
        "y": 0.9566
      },
      {
        "x": -0.59896,
        "y": 0.9566
      },
      {
        "x": -1,
        "y": -0.21528
      }
    ]
  },
  "regularHexagon": {
    "image": "assets/option-shape/regularHexagon.webp",
    "sides": 6,
    "regular": true,
    "convex": true,
    "aspect": 1.15355,
    "points": [
      {
        "x": -0.50083,
        "y": -0.86689
      },
      {
        "x": 0.49917,
        "y": -0.86689
      },
      {
        "x": 0.99834,
        "y": 0
      },
      {
        "x": 0.49917,
        "y": 0.86522
      },
      {
        "x": -0.50083,
        "y": 0.86522
      },
      {
        "x": -1,
        "y": -0.00166
      }
    ]
  },
  "regularHeptagon": {
    "image": "assets/option-shape/regularHeptagon.webp",
    "sides": 7,
    "regular": true,
    "convex": true,
    "aspect": 1.03425,
    "points": [
      {
        "x": -0.00662,
        "y": -0.96689
      },
      {
        "x": 0.80629,
        "y": -0.51656
      },
      {
        "x": 0.99586,
        "y": 0.31871
      },
      {
        "x": 0.43377,
        "y": 0.96523
      },
      {
        "x": -0.44371,
        "y": 0.96358
      },
      {
        "x": -1,
        "y": 0.32119
      },
      {
        "x": -0.80795,
        "y": -0.51656
      }
    ]
  },
  "regularOctagon": {
    "image": "assets/option-shape/regularOctagon.webp",
    "sides": 8,
    "regular": true,
    "convex": true,
    "aspect": 1.01629,
    "points": [
      {
        "x": -0.38736,
        "y": -0.98397
      },
      {
        "x": 0.38914,
        "y": -0.98397
      },
      {
        "x": 0.99644,
        "y": -0.38023
      },
      {
        "x": 0.99644,
        "y": 0.3927
      },
      {
        "x": 0.40516,
        "y": 0.98219
      },
      {
        "x": -0.41407,
        "y": 0.98219
      },
      {
        "x": -0.99822,
        "y": 0.39448
      },
      {
        "x": -0.99822,
        "y": -0.38023
      }
    ]
  },
  "irregularPentagon": {
    "image": "assets/option-shape/irregularPentagon.webp",
    "sides": 5,
    "regular": false,
    "convex": true,
    "aspect": 1.01925,
    "points": [
      {
        "x": -0.00086,
        "y": -0.98112
      },
      {
        "x": 0.99828,
        "y": -0.24464
      },
      {
        "x": 0.55708,
        "y": 0.9794
      },
      {
        "x": -0.58455,
        "y": 0.9794
      },
      {
        "x": -1,
        "y": -0.25494
      }
    ]
  },
  "irregularConvexPentagon": {
    "image": "assets/option-shape/irregularConvexPentagon.webp",
    "sides": 5,
    "regular": false,
    "convex": true,
    "aspect": 0.99213,
    "points": [
      {
        "x": -0.44969,
        "y": -1
      },
      {
        "x": 0.99038,
        "y": -0.03762
      },
      {
        "x": 0.44619,
        "y": 0.99475
      },
      {
        "x": -0.55643,
        "y": 0.99825
      },
      {
        "x": -0.99213,
        "y": 0.42432
      }
    ]
  },
  "irregularHexagon": {
    "image": "assets/option-shape/irregularHexagon.webp",
    "sides": 6,
    "regular": false,
    "convex": true,
    "aspect": 0.88297,
    "points": [
      {
        "x": -0.19476,
        "y": -1
      },
      {
        "x": 0.39563,
        "y": -0.99476
      },
      {
        "x": 0.88122,
        "y": -0.05153
      },
      {
        "x": 0.62795,
        "y": 0.98603
      },
      {
        "x": -0.40961,
        "y": 0.99825
      },
      {
        "x": -0.88297,
        "y": 0.02009
      }
    ]
  },
  "irregularConvexHexagon": {
    "image": "assets/option-shape/irregularConvexHexagon.webp",
    "sides": 6,
    "regular": false,
    "convex": true,
    "aspect": 1.12072,
    "points": [
      {
        "x": -0.45717,
        "y": -0.89228
      },
      {
        "x": 0.45886,
        "y": -0.89228
      },
      {
        "x": 0.9983,
        "y": 0.00848
      },
      {
        "x": 0.47243,
        "y": 0.88889
      },
      {
        "x": -0.48261,
        "y": 0.88889
      },
      {
        "x": -0.99491,
        "y": 0.01866
      }
    ]
  },
  "irregularConvexOctagon": {
    "image": "assets/option-shape/irregularConvexOctagon.webp",
    "sides": 8,
    "regular": false,
    "convex": true,
    "aspect": 1.0165,
    "points": [
      {
        "x": 0.33634,
        "y": -0.97836
      },
      {
        "x": 0.9982,
        "y": -0.36159
      },
      {
        "x": 0.85573,
        "y": 0.54193
      },
      {
        "x": 0.33093,
        "y": 0.98197
      },
      {
        "x": -0.35257,
        "y": 0.98016
      },
      {
        "x": -0.86294,
        "y": 0.53472
      },
      {
        "x": -0.9982,
        "y": -0.38503
      },
      {
        "x": -0.33003,
        "y": -0.97746
      }
    ]
  },
  "concavePentagon": {
    "image": "assets/option-shape/concavePentagon.webp",
    "sides": 5,
    "regular": false,
    "convex": false,
    "aspect": 0.95833,
    "points": [
      {
        "x": -0.00245,
        "y": -1
      },
      {
        "x": 0.9567,
        "y": -0.38889
      },
      {
        "x": 0.60539,
        "y": 0.99837
      },
      {
        "x": 0.01552,
        "y": 0.20752
      },
      {
        "x": -0.95833,
        "y": 0.49673
      }
    ]
  },
  "concaveHexagon": {
    "image": "assets/option-shape/concaveHexagon.webp",
    "sides": 6,
    "regular": false,
    "convex": false,
    "aspect": 1.158,
    "points": [
      {
        "x": 0.90849,
        "y": -0.86356
      },
      {
        "x": 0.99667,
        "y": 0.31947
      },
      {
        "x": 0.04659,
        "y": 0.8619
      },
      {
        "x": -1,
        "y": 0.27787
      },
      {
        "x": -0.91015,
        "y": -0.82196
      },
      {
        "x": 0.00998,
        "y": -0.18469
      }
    ]
  },
  "concaveHeptagon": {
    "image": "assets/option-shape/concaveHeptagon.webp",
    "sides": 7,
    "regular": false,
    "convex": false,
    "aspect": 1.19268,
    "points": [
      {
        "x": -0.52888,
        "y": -0.83845
      },
      {
        "x": 0.00542,
        "y": -0.33845
      },
      {
        "x": 0.54693,
        "y": -0.76083
      },
      {
        "x": 0.99819,
        "y": 0.27166
      },
      {
        "x": 0.57942,
        "y": 0.83664
      },
      {
        "x": -0.57762,
        "y": 0.83664
      },
      {
        "x": -1,
        "y": 0.23736
      }
    ]
  }
};

/** The ring for a shape, or null if the art does not cover it. */
export function shapeRing(id) {
  const s = optionShapes[id];
  return s ? s.points : null;
}

/** How many sides a shape has, measured from its own artwork. */
export function shapeSides(id) {
  const s = optionShapes[id];
  return s ? s.sides : 0;
}
