/*!
 * sfx.js — comic / arcade sound effects, synthesised at runtime.
 *
 * No audio files. No network. No dependencies. No licence obligations —
 * every sound is generated by the Web Audio API on the user's machine.
 *
 *   <script src="sfx.js"></script>
 *   SFX.play('coin');
 *   SFX.play('boing', { pitch: 1.4, volume: 0.5 });
 *   SFX.volume(0.4);
 *
 * Mix chain:
 *
 *     recipes ──┐
 *   Pack (sfx) ─┴─ sfxBus ──┐   (ducked under voice)
 *        music ──── musicBus┼── master ── limiter ── analyser ── out
 *        voice ──── voiceBus┘   (never ducked; triggers the duck)
 *
 * Three things the naive version got wrong, fixed here:
 *   - Voice-over is drowned by effects. Route speech through voiceBus and
 *     the effects duck under it automatically.
 *   - Firing many cues at once clips. Per-sound voice caps plus a master
 *     limiter.
 *   - Hand-tuned levels drift up to 27 dB apart. The TRIM table below is
 *     measured, not guessed — see tools/measure-loudness.js.
 */
(function (global) {
  'use strict';

  var AC = global.AudioContext || global.webkitAudioContext;

  var ctx = null;
  var master = null, limiter = null, scope = null;
  var sfxBus = null, voiceBus = null, musicBus = null;
  var out = null;            // current destination for primitives
  var noiseBuf = null;
  var muted = false;
  var masterVol = 0.6;

  var cfg = {
    maxVoices:   4,      // per sound name; oldest is stolen beyond this
    duckTo:      0.25,   // sfxBus gain while voice is playing
    duckMusicTo: 0.15,
    duckAttack:  0.08,   // seconds
    duckRelease: 0.30,
    limiter:     true,
    clipKnee:    0.70   // soft clip engages only above this amplitude
  };

  /* ------------------------------------------------------------------ *
   * Calibration — GENERATED by tools/measure-loudness.js. Do not hand-edit;
   * re-run the tool instead.
   *
   * TRIM brings each sound to its family target (interface -27, movement
   * -23, cartoon -22, reward -20, drama -18 LUFS). Those targets are a mix
   * decision: a UI tick is meant to sit under an explosion, so this is
   * deliberately not flat normalisation.
   *
   * DUR is the measured decay to -60 dBFS, used to retire finished voices.
   * ------------------------------------------------------------------ */

  var TRIM = {
    coin:            0.734,
    gem:             1.097,
    powerUp:         0.804,
    levelUp:         0.892,
    sparkle:         1.912,
    correct:         0.944,
    jump:            0.920,
    doubleJump:      1.077,
    boing:           0.684,
    swoosh:          1.261,
    slice:           1.069,
    land:            1.266,
    pop:             1.380,
    bubble:          1.425,
    squeak:          1.095,
    splat:           1.355,
    honk:            1.058,
    slideWhistle:    0.788,
    click:           1.504,
    select:          0.902,
    tick:            1.118,
    wrong:           0.491,
    error:           0.639,
    menuWhoosh:      1.350,
    laser:           1.040,
    explode:         1.398,
    hurt:            1.331,
    gameOver:        1.018,
    alarm:           1.067,
    sadTrombone:     0.890,
    rimshot:         0.632,
    bonk:            1.246,
    doink:           1.001,
    ratchet:         0.966,
    anticipate:      0.830,
    zip:             1.095,
    recordScratch:   0.951,
    cuckoo:          0.866,
    rubberChicken:   1.106,
    ricochet:        1.045,
    pianoRun:        0.995,
    fallingWhistle:  0.442,
    kazoo:           1.030,
    drumroll:        0.666,
    powerDown:       0.802
  };

  var DUR = {
    coin:            0.32,
    gem:             0.33,
    powerUp:         0.50,
    levelUp:         0.74,
    sparkle:         0.36,
    correct:         0.44,
    jump:            0.12,
    doubleJump:      0.23,
    boing:           0.33,
    swoosh:          0.32,
    slice:           0.12,
    land:            0.12,
    pop:             0.07,
    bubble:          0.10,
    squeak:          0.21,
    splat:           0.16,
    honk:            0.39,
    slideWhistle:    0.56,
    click:           0.03,
    select:          0.07,
    tick:            0.04,
    wrong:           0.43,
    error:           0.25,
    menuWhoosh:      0.28,
    laser:           0.18,
    explode:         0.42,
    hurt:            0.22,
    gameOver:        1.07,
    alarm:           0.75,
    sadTrombone:     1.45,
    rimshot:         1.27,
    bonk:            0.06,
    doink:           0.23,
    ratchet:         0.61,
    anticipate:      0.46,
    zip:             0.13,
    recordScratch:   0.30,
    cuckoo:          0.52,
    rubberChicken:   0.28,
    ricochet:        0.33,
    pianoRun:        0.67,
    fallingWhistle:  0.84,
    kazoo:           0.25,
    drumroll:        1.81,
    powerDown:       0.51
  };

  var FLOOR = 0.0001;   // exponential ramps can never reach exactly zero

  /* ------------------------------------------------------------------ *
   * Musical key
   *
   * The reason a Mario coin is charming is not that it is funny — it is
   * that it is consonant. Every Nintendo cue is pitched to sit in the level
   * music. Set a key and sustained notes snap to that scale, so thirty cues
   * stop arguing with each other and with your soundtrack.
   *
   * Glides are never snapped: a jump sweep or a laser drop is a gesture,
   * not a note, and quantising it would flatten the gesture.
   * ------------------------------------------------------------------ */

  var SCALES = {
    chromatic:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    major:      [0, 2, 4, 5, 7, 9, 11],
    minor:      [0, 2, 3, 5, 7, 8, 10],
    pentatonic: [0, 2, 4, 7, 9],           // nothing can clash. Best default.
    minorPentatonic: [0, 3, 5, 7, 10],
    blues:      [0, 3, 5, 6, 7, 10],
    wholeTone:  [0, 2, 4, 6, 8, 10],       // dreamy, unmoored — cartoon float
    lydian:     [0, 2, 4, 6, 7, 9, 11]     // bright, "magic"
  };

  var NOTES = { C:0, 'C#':1, DB:1, D:2, 'D#':3, EB:3, E:4, F:5, 'F#':6,
                GB:6, G:7, 'G#':8, AB:8, A:9, 'A#':10, BB:10, B:11 };

  var keyRoot = null, keySet = null, keyName = null;

  function setKey(spec) {
    if (spec == null || spec === false) {
      keyRoot = keySet = keyName = null;
      return null;
    }
    var m = String(spec).trim().match(/^([A-Ga-g][#b]?)\s*(.*)$/);
    if (!m) { if (global.console) console.warn('SFX: bad key "' + spec + '"'); return keyName; }

    var root = NOTES[m[1].toUpperCase()];
    var raw = (m[2] || 'major').replace(/[\s_-]/g, '');
    var name = null;
    for (var k in SCALES) {
      if (k.toLowerCase() === raw.toLowerCase()) { name = k; break; }
    }
    if (root == null || !name) {
      if (global.console) console.warn('SFX: unknown key "' + spec + '"');
      return keyName;
    }
    keyRoot = root;
    keySet = SCALES[name];
    keyName = m[1].toUpperCase().charAt(0) + m[1].slice(1) + ' ' + name;
    return keyName;
  }

  /** Nearest frequency in the current scale. Identity when no key is set. */
  function snap(f) {
    if (!keySet || !(f > 0)) return f;
    var midi = 69 + 12 * Math.log(f / 440) / Math.LN2;
    var centre = Math.round(midi);
    var best = null, bestD = Infinity;
    for (var m = centre - 6; m <= centre + 6; m++) {
      var pc = ((m - keyRoot) % 12 + 12) % 12;
      if (keySet.indexOf(pc) < 0) continue;
      var d = Math.abs(m - midi);
      if (d < bestD) { bestD = d; best = m; }
    }
    return best == null ? f : 440 * Math.pow(2, (best - 69) / 12);
  }

  function ensure() {
    if (!AC) return null;
    if (!ctx) {
      ctx = new AC();

      master = ctx.createGain();
      master.gain.value = muted ? 0 : masterVol;

      sfxBus   = ctx.createGain();
      voiceBus = ctx.createGain();
      musicBus = ctx.createGain();
      sfxBus.connect(master);
      voiceBus.connect(master);
      musicBus.connect(master);

      scope = ctx.createAnalyser();
      scope.fftSize = 2048;
      scope.smoothingTimeConstant = 0.6;
      scope.connect(ctx.destination);

      out = sfxBus;

      wireOutput();
    }
    // Only realtime contexts get auto-resumed. An OfflineAudioContext is
    // driven by startRendering and reports 'suspended' between frames, so
    // resuming it from here would corrupt a render — which is exactly what
    // tools/measure-loudness.js does.
    if (ctx.state === 'suspended' && ctx.resume && !ctx.startRendering) ctx.resume();
    return ctx;
  }

  /** (Re)connect master -> [limiter] -> analyser -> out. Safe to call again. */
  function wireOutput() {
    try { master.disconnect(); } catch (e) {}
    if (limiter) { try { limiter.disconnect(); } catch (e) {} limiter = null; }

    if (cfg.limiter && ctx.createWaveShaper) {
      // NOT a DynamicsCompressor. That node applies an internal makeup gain
      // (measured at +3.4 dB with limiter settings) which differs between
      // engines, so it would silently undo the calibration above — and undo
      // it by a different amount in Chrome than in Firefox. A WaveShaper
      // curve is fully specified, identical everywhere, exactly unity below
      // the knee, and can never boost.
      limiter = ctx.createWaveShaper();
      limiter.curve = softClip(cfg.clipKnee);
      limiter.oversample = '4x';
      master.connect(limiter);
      limiter.connect(scope);
    } else {
      master.connect(scope);
    }
  }

  /**
   * Soft-clip transfer curve: exactly y = x below `knee`, then a tanh
   * shoulder that asymptotes to 1. Transparent at normal levels; only
   * stacked cues ever reach the curved region.
   */
  function softClip(knee) {
    var n = 8192, curve = new Float32Array(n);
    var span = 1 - knee;
    for (var i = 0; i < n; i++) {
      var x = (i / (n - 1)) * 2 - 1;
      var a = Math.abs(x);
      var y = a <= knee ? a : knee + span * Math.tanh((a - knee) / span);
      curve[i] = x < 0 ? -y : y;
    }
    return curve;
  }

  function noise() {
    if (noiseBuf) return noiseBuf;
    var len = Math.floor(ctx.sampleRate * 1.5);
    noiseBuf = ctx.createBuffer(1, len, ctx.sampleRate);
    var d = noiseBuf.getChannelData(0);
    for (var i = 0; i < len; i++) d[i] = Math.random() * 2 - 1;
    return noiseBuf;
  }

  /** Cancel whatever is scheduled and glide to a new value. */
  function glide(param, to, seconds) {
    var t = ctx.currentTime;
    var current = param.value;
    try { param.cancelScheduledValues(t); } catch (e) {}
    param.setValueAtTime(current, t);
    param.linearRampToValueAtTime(to, t + seconds);
  }

  /* ------------------------------------------------------------------ *
   * Primitives
   * ------------------------------------------------------------------ */

  /**
   * A pitched tone with an optional frequency glide and optional filter.
   * o = { at, from, to, dur, type, vol, attack, glide, filter:{type,from,to,q} }
   */
  function blip(o) {
    var t = o.at;
    var dur = o.dur;
    var osc = ctx.createOscillator();
    var g = ctx.createGain();

    osc.type = o.type || 'square';
    // A note with no glide is a pitch and gets quantised to the key. A note
    // with a glide is a gesture and is left alone.
    var f0 = (o.to == null && o.tonal !== false) ? snap(o.from) : o.from;
    osc.frequency.setValueAtTime(Math.max(1, f0), t);
    if (o.to != null && o.to !== o.from) {
      if (o.glide === 'linear') {
        osc.frequency.linearRampToValueAtTime(Math.max(1, o.to), t + dur);
      } else {
        osc.frequency.exponentialRampToValueAtTime(Math.max(1, o.to), t + dur);
      }
    }

    var peak = o.vol == null ? 0.3 : o.vol;
    var atk = o.attack == null ? 0.004 : o.attack;
    g.gain.setValueAtTime(FLOOR, t);
    g.gain.exponentialRampToValueAtTime(peak, t + atk);
    g.gain.exponentialRampToValueAtTime(FLOOR, t + dur);

    if (o.filter) {
      var f = ctx.createBiquadFilter();
      f.type = o.filter.type || 'lowpass';
      f.Q.value = o.filter.q == null ? 1 : o.filter.q;
      f.frequency.setValueAtTime(Math.max(20, o.filter.from), t);
      if (o.filter.to != null) {
        f.frequency.exponentialRampToValueAtTime(Math.max(20, o.filter.to), t + dur);
      }
      osc.connect(f);
      f.connect(g);
    } else {
      osc.connect(g);
    }

    g.connect(out);
    osc.start(t);
    osc.stop(t + dur + 0.03);
  }

  /**
   * A filtered noise burst — impacts, whooshes, slices, explosions.
   * o = { at, from, to, dur, filter, q, vol, attack }
   */
  function hiss(o) {
    var t = o.at;
    var dur = o.dur;
    var src = ctx.createBufferSource();
    src.buffer = noise();

    var f = ctx.createBiquadFilter();
    f.type = o.filter || 'bandpass';
    f.Q.value = o.q == null ? 1 : o.q;
    f.frequency.setValueAtTime(Math.max(20, o.from), t);
    f.frequency.exponentialRampToValueAtTime(Math.max(20, o.to == null ? o.from : o.to), t + dur);

    var g = ctx.createGain();
    var peak = o.vol == null ? 0.3 : o.vol;
    var atk = o.attack == null ? 0.005 : o.attack;
    g.gain.setValueAtTime(FLOOR, t);
    g.gain.exponentialRampToValueAtTime(peak, t + atk);
    g.gain.exponentialRampToValueAtTime(FLOOR, t + dur);

    src.connect(f);
    f.connect(g);
    g.connect(out);
    src.start(t, Math.random() * 0.3);
    src.stop(t + dur + 0.03);
  }

  /** A tone whose pitch wobbles — springs, rubber, cartoon bounce. */
  function wobbler(o) {
    var t = o.at;
    var dur = o.dur;
    var osc = ctx.createOscillator();
    var g = ctx.createGain();
    var lfo = ctx.createOscillator();
    var depth = ctx.createGain();

    osc.type = o.type || 'sine';
    osc.frequency.setValueAtTime(Math.max(1, o.from), t);
    osc.frequency.exponentialRampToValueAtTime(Math.max(1, o.to), t + dur);

    lfo.type = 'sine';
    lfo.frequency.setValueAtTime(o.rate || 20, t);
    lfo.frequency.exponentialRampToValueAtTime(o.rateEnd || 6, t + dur);
    depth.gain.setValueAtTime(o.depth || 200, t);
    depth.gain.exponentialRampToValueAtTime(4, t + dur);
    lfo.connect(depth);
    depth.connect(osc.frequency);

    var peak = o.vol == null ? 0.3 : o.vol;
    g.gain.setValueAtTime(FLOOR, t);
    g.gain.exponentialRampToValueAtTime(peak, t + 0.008);
    g.gain.exponentialRampToValueAtTime(FLOOR, t + dur);

    if (o.filter) {
      var wf = ctx.createBiquadFilter();
      wf.type = o.filter.type || 'bandpass';
      wf.Q.value = o.filter.q == null ? 1 : o.filter.q;
      wf.frequency.setValueAtTime(Math.max(20, o.filter.from), t);
      if (o.filter.to != null) {
        wf.frequency.exponentialRampToValueAtTime(Math.max(20, o.filter.to), t + dur);
      }
      osc.connect(wf); wf.connect(g);
    } else {
      osc.connect(g);
    }
    g.connect(out);
    osc.start(t); lfo.start(t);
    osc.stop(t + dur + 0.03); lfo.stop(t + dur + 0.03);
  }

  /* ------------------------------------------------------------------ *
   * Recipes.  Each receives (t, p): start time and a pitch multiplier.
   * ------------------------------------------------------------------ */

  var recipes = {

    /* --- pickups & rewards ----------------------------------------- */

    coin: function (t, p) {
      blip({ at: t,        from: 988 * p,  dur: 0.07, type: 'square', vol: 0.26 });
      blip({ at: t + 0.07, from: 1319 * p, dur: 0.34, type: 'square', vol: 0.26 });
    },

    gem: function (t, p) {
      [1047, 1319, 1568].forEach(function (f, i) {
        blip({ at: t + i * 0.05, from: f * p, dur: 0.3, type: 'triangle', vol: 0.22 });
      });
    },

    powerUp: function (t, p) {
      [523, 659, 784, 1047, 1319].forEach(function (f, i) {
        blip({ at: t + i * 0.045, from: f * p, dur: 0.11, type: 'square', vol: 0.17 });
      });
      blip({ at: t + 0.225, from: 1568 * p, dur: 0.38, type: 'square', vol: 0.2 });
    },

    levelUp: function (t, p) {
      var seq = [[392, 0.1], [392, 0.1], [392, 0.1], [523, 0.5]];
      var o = 0;
      seq.forEach(function (s) {
        blip({ at: t + o, from: s[0] * p,       dur: s[1], type: 'square',   vol: 0.19 });
        blip({ at: t + o, from: s[0] * 1.5 * p, dur: s[1], type: 'triangle', vol: 0.11 });
        o += s[1] + 0.015;
      });
    },

    sparkle: function (t, p) {
      for (var i = 0; i < 7; i++) {
        blip({
          at: t + i * 0.042,
          from: (1400 + Math.random() * 1700) * p,
          dur: 0.15, type: 'triangle', vol: 0.12
        });
      }
    },

    correct: function (t, p) {
      blip({ at: t,        from: 659 * p,  dur: 0.16, type: 'sine', vol: 0.28 });
      blip({ at: t + 0.09, from: 988 * p,  dur: 0.44, type: 'sine', vol: 0.26 });
      blip({ at: t + 0.09, from: 1319 * p, dur: 0.44, type: 'sine', vol: 0.11 });
    },

    /* --- movement --------------------------------------------------- */

    jump: function (t, p) {
      blip({ at: t, from: 180 * p, to: 760 * p, dur: 0.16, type: 'square', vol: 0.26 });
    },

    doubleJump: function (t, p) {
      blip({ at: t,        from: 220 * p, to: 820 * p,  dur: 0.13, type: 'square', vol: 0.24 });
      blip({ at: t + 0.11, from: 330 * p, to: 1180 * p, dur: 0.15, type: 'square', vol: 0.2 });
    },

    boing: function (t, p) {
      wobbler({ at: t, from: 560 * p, to: 150 * p, dur: 0.45, depth: 230 * p, rate: 22, vol: 0.3 });
    },

    swoosh: function (t, p) {
      hiss({ at: t,        from: 300 * p,  to: 2400 * p, dur: 0.19, filter: 'bandpass', q: 1.1, vol: 0.85, attack: 0.1 });
      hiss({ at: t + 0.17, from: 2400 * p, to: 420 * p,  dur: 0.22, filter: 'bandpass', q: 1.1, vol: 0.66, attack: 0.02 });
    },

    slice: function (t, p) {
      hiss({ at: t, from: 2800 * p, to: 700 * p, dur: 0.16, filter: 'bandpass', q: 3, vol: 0.9, attack: 0.004 });
      blip({ at: t, from: 1800 * p, to: 400 * p, dur: 0.14, type: 'sawtooth', vol: 0.21 });
    },

    land: function (t, p) {
      hiss({ at: t, from: 320 * p, to: 80 * p, dur: 0.14, filter: 'lowpass', q: 0.7, vol: 0.32 });
      blip({ at: t, from: 140 * p, to: 55 * p, dur: 0.16, type: 'sine', vol: 0.3 });
    },

    /* --- cartoon ---------------------------------------------------- */

    pop: function (t, p) {
      blip({ at: t, from: 900 * p, to: 180 * p, dur: 0.09, type: 'sine', vol: 0.36, attack: 0.002 });
    },

    bubble: function (t, p) {
      blip({ at: t, from: 280 * p, to: 1100 * p, dur: 0.13, type: 'sine', vol: 0.3 });
    },

    squeak: function (t, p) {
      blip({ at: t, from: 900 * p, to: 1900 * p, dur: 0.1, type: 'sawtooth', vol: 0.28,
             filter: { type: 'lowpass', from: 3200, to: 5200, q: 6 } });
      blip({ at: t + 0.1, from: 1900 * p, to: 800 * p, dur: 0.13, type: 'sawtooth', vol: 0.28,
             filter: { type: 'lowpass', from: 5200, to: 2400, q: 6 } });
    },

    splat: function (t, p) {
      hiss({ at: t, from: 1800 * p, to: 120 * p, dur: 0.22, filter: 'lowpass', q: 1, vol: 0.36, attack: 0.003 });
      blip({ at: t, from: 220 * p,  to: 60 * p,  dur: 0.2,  type: 'triangle', vol: 0.28 });
    },

    honk: function (t, p) {
      blip({ at: t, from: 330 * p, dur: 0.16, type: 'sawtooth', vol: 0.32,
             filter: { type: 'lowpass', from: 1400, to: 900, q: 4 } });
      blip({ at: t + 0.18, from: 262 * p, dur: 0.26, type: 'sawtooth', vol: 0.32,
             filter: { type: 'lowpass', from: 1200, to: 700, q: 4 } });
    },

    slideWhistle: function (t, p) {
      blip({ at: t,       from: 600 * p,  to: 1900 * p, dur: 0.3,  type: 'sine', vol: 0.24 });
      blip({ at: t + 0.3, from: 1900 * p, to: 500 * p,  dur: 0.36, type: 'sine', vol: 0.24 });
    },

    /* --- interface -------------------------------------------------- */

    click: function (t, p) {
      hiss({ at: t, from: 2200 * p, to: 1400 * p, dur: 0.035, filter: 'bandpass', q: 2, vol: 1.2, attack: 0.001 });
    },

    select: function (t, p) {
      blip({ at: t, from: 660 * p, to: 990 * p, dur: 0.09, type: 'square', vol: 0.2 });
    },

    tick: function (t, p) {
      blip({ at: t, from: 1200 * p, dur: 0.05, type: 'square', vol: 0.2 });
    },

    wrong: function (t, p) {
      blip({ at: t,        from: 311 * p, dur: 0.18, type: 'square', vol: 0.2 });
      blip({ at: t + 0.17, from: 233 * p, dur: 0.36, type: 'square', vol: 0.2 });
    },

    error: function (t, p) {
      blip({ at: t, from: 180 * p, dur: 0.3, type: 'sawtooth', vol: 0.17,
             filter: { type: 'lowpass', from: 900, to: 400, q: 2 } });
      blip({ at: t, from: 184 * p, dur: 0.3, type: 'sawtooth', vol: 0.17,
             filter: { type: 'lowpass', from: 900, to: 400, q: 2 } });
    },

    menuWhoosh: function (t, p) {
      hiss({ at: t, from: 200 * p, to: 1800 * p, dur: 0.35, filter: 'lowpass', q: 0.8, vol: 0.8, attack: 0.14 });
    },

    /* --- drama ------------------------------------------------------ */

    laser: function (t, p) {
      blip({ at: t, from: 1800 * p, to: 180 * p, dur: 0.22, type: 'sawtooth', vol: 0.36,
             filter: { type: 'lowpass', from: 4000, to: 600, q: 6 } });
    },

    explode: function (t, p) {
      hiss({ at: t, from: 1400 * p, to: 60 * p, dur: 0.7, filter: 'lowpass', q: 1.2, vol: 0.4, attack: 0.005 });
      blip({ at: t, from: 120 * p,  to: 40 * p, dur: 0.5, type: 'triangle', vol: 0.3 });
    },

    hurt: function (t, p) {
      blip({ at: t, from: 420 * p, to: 130 * p, dur: 0.3, type: 'square', vol: 0.22 });
      hiss({ at: t, from: 900 * p, to: 200 * p, dur: 0.18, filter: 'bandpass', q: 1, vol: 0.11 });
    },

    gameOver: function (t, p) {
      [523, 466, 415, 349].forEach(function (f, i) {
        blip({ at: t + i * 0.19, from: f * p, dur: i === 3 ? 0.7 : 0.19, type: 'square', vol: 0.2 });
      });
    },

    alarm: function (t, p) {
      for (var i = 0; i < 3; i++) {
        blip({ at: t + i * 0.26,        from: 880 * p,  to: 1200 * p, dur: 0.12, type: 'square', vol: 0.4 });
        blip({ at: t + i * 0.26 + 0.13, from: 1200 * p, to: 880 * p,  dur: 0.12, type: 'square', vol: 0.4 });
      }
    },


    /* --- comic ------------------------------------------------------ *
     * These are the gestures cartoon scoring actually uses. The arcade
     * family above is 8-bit vocabulary; none of it is funny on its own.
     * ---------------------------------------------------------------- */

    /** Wah-wah-wah-waaah. The single most legible comic failure. */
    sadTrombone: function (t, p) {
      var notes = [[233, 0.26], [220, 0.26], [208, 0.26], [196, 0.80]];
      var o = 0;
      for (var i = 0; i < notes.length; i++) {
        var f = notes[i][0] * p, d = notes[i][1];
        var last = i === notes.length - 1;
        blip({
          at: t + o, from: f, to: f * (last ? 0.68 : 0.945), dur: d,
          type: 'sawtooth', vol: 0.34, glide: 'linear', attack: 0.03,
          filter: { type: 'lowpass', from: last ? 1500 : 1300,
                    to: last ? 480 : 780, q: 4 }
        });
        o += d + 0.015;
      }
    },

    /** Ba-dum-tss. The punchline. */
    rimshot: function (t, p) {
      blip({ at: t, from: 200 * p, to: 90 * p, dur: 0.14, type: 'sine', vol: 0.45 });
      hiss({ at: t, from: 2000, to: 900, dur: 0.09, filter: 'bandpass', q: 1.2, vol: 0.32 });
      blip({ at: t + 0.18, from: 170 * p, to: 78 * p, dur: 0.16, type: 'sine', vol: 0.45 });
      hiss({ at: t + 0.18, from: 1800, to: 800, dur: 0.11, filter: 'bandpass', q: 1.2, vol: 0.32 });
      hiss({ at: t + 0.36, from: 6200, to: 3200, dur: 1.15, filter: 'highpass',
             q: 0.7, vol: 0.4, attack: 0.004 });
    },

    /** Wood block. Dry, pitched, no tail. */
    bonk: function (t, p) {
      blip({ at: t, from: 810 * p, to: 720 * p, dur: 0.075, type: 'sine', vol: 0.5, attack: 0.001 });
      hiss({ at: t, from: 1700 * p, to: 1100 * p, dur: 0.035, filter: 'bandpass',
             q: 9, vol: 0.4, attack: 0.001 });
    },

    /** Softer, rounder bonk with a bit of rubber in it. */
    doink: function (t, p) {
      wobbler({ at: t, from: 700 * p, to: 210 * p, dur: 0.3, depth: 130 * p,
                rate: 15, vol: 0.38, type: 'triangle' });
    },

    /** Accelerating wind-up. Setup, not payoff — hence the lower target. */
    ratchet: function (t, p) {
      var o = 0, gap = 0.062;
      for (var i = 0; i < 15; i++) {
        hiss({ at: t + o, from: (1300 + i * 95) * p, to: (850 + i * 60) * p,
               dur: 0.03, filter: 'bandpass', q: 7, vol: 2.2, attack: 0.001 });
        gap *= 0.945;
        o += gap;
      }
    },

    /** Rising tension: a glide plus an accelerating tick. Pairs with any payoff. */
    anticipate: function (t, p) {
      blip({ at: t, from: 230 * p, to: 920 * p, dur: 0.62, type: 'triangle',
             vol: 0.24, glide: 'linear' });
      var o = 0, gap = 0.1;
      for (var i = 0; i < 9; i++) {
        hiss({ at: t + o, from: 2300, to: 1700, dur: 0.028, filter: 'bandpass',
               q: 7, vol: 0.16, attack: 0.001 });
        gap *= 0.86;
        o += gap;
      }
    },

    zip: function (t, p) {
      hiss({ at: t, from: 420 * p, to: 5200 * p, dur: 0.15, filter: 'bandpass',
             q: 4, vol: 1.5, attack: 0.02 });
      blip({ at: t, from: 320 * p, to: 2500 * p, dur: 0.15, type: 'sawtooth', vol: 0.43,
             filter: { type: 'lowpass', from: 1200, to: 6000, q: 3 } });
    },

    recordScratch: function (t, p) {
      var segs = [[600, 3000, 0.09], [3000, 520, 0.07], [520, 2400, 0.08], [2400, 420, 0.12]];
      var o = 0;
      for (var i = 0; i < segs.length; i++) {
        hiss({ at: t + o, from: segs[i][0] * p, to: segs[i][1] * p, dur: segs[i][2],
               filter: 'bandpass', q: 3, vol: 2.2, attack: 0.005 });
        o += segs[i][2] * 0.9;
      }
    },

    /** Falling minor third, soft attack. */
    cuckoo: function (t, p) {
      blip({ at: t,        from: 784 * p, dur: 0.22, type: 'sine', vol: 0.36, attack: 0.02 });
      blip({ at: t + 0.25, from: 659 * p, dur: 0.36, type: 'sine', vol: 0.33, attack: 0.02 });
    },

    rubberChicken: function (t, p) {
      wobbler({ at: t, from: 520 * p, to: 330 * p, dur: 0.44, depth: 240 * p,
                rate: 17, rateEnd: 9, vol: 1.0, type: 'sawtooth',
                filter: { type: 'bandpass', from: 1250, to: 900, q: 6 } });
    },

    /** Pew-ee-ow, three decaying bounces. */
    ricochet: function (t, p) {
      var offs = [0, 0.115, 0.25];
      for (var i = 0; i < offs.length; i++) {
        blip({ at: t + offs[i], from: (2700 - i * 420) * p, to: (720 - i * 150) * p,
               dur: 0.13, type: 'sawtooth', vol: 0.5 * Math.pow(0.6, i),
               filter: { type: 'bandpass', from: 2700, to: 800, q: 5 } });
      }
    },

    /** Descending run. Snaps to the key when one is set, so it lands in tune. */
    pianoRun: function (t, p) {
      var notes = [1047, 988, 880, 784, 698, 659, 587, 523];
      for (var i = 0; i < notes.length; i++) {
        blip({ at: t + i * 0.055, from: notes[i] * p, dur: 0.38,
               type: 'triangle', vol: 0.22, attack: 0.003 });
      }
    },

    /** The long descending whistle before something lands. */
    fallingWhistle: function (t, p) {
      blip({ at: t, from: 1900 * p, to: 210 * p, dur: 1.15, type: 'sine',
             vol: 0.32, attack: 0.04 });
    },

    kazoo: function (t, p) {
      wobbler({ at: t, from: 445 * p, to: 425 * p, dur: 0.42, depth: 14 * p,
                rate: 32, rateEnd: 27, vol: 0.58, type: 'square',
                filter: { type: 'bandpass', from: 1350, to: 1500, q: 9 } });
    },

    /** Snare roll into a crash. Use before a reveal. */
    drumroll: function (t, p) {
      var o = 0;
      for (var i = 0; i < 24; i++) {
        hiss({ at: t + o, from: 2100, to: 1250, dur: 0.05, filter: 'bandpass',
               q: 1.5, vol: 0.14 + i * 0.009, attack: 0.002 });
        o += 0.045;
      }
      hiss({ at: t + o, from: 6200, to: 3000, dur: 0.95, filter: 'highpass',
             q: 0.7, vol: 0.4, attack: 0.004 });
    },

    powerDown: function (t, p) {
      blip({ at: t, from: 900 * p, to: 90 * p, dur: 0.7, type: 'square', vol: 0.24 });
    }
  };

  /* ------------------------------------------------------------------ *
   * Voice management — cap concurrent copies of each sound and steal the
   * oldest when the cap is hit. Without this, a burst of cues in one frame
   * sums into clipping and mush.
   * ------------------------------------------------------------------ */

  var active = {};   // name -> [{ gain, until }]

  function reserve(name) {
    var list = active[name] || (active[name] = []);
    var now = ctx.currentTime;

    for (var i = list.length - 1; i >= 0; i--) {
      if (list[i].until <= now) list.splice(i, 1);
    }

    while (list.length >= cfg.maxVoices) {
      var oldest = list.shift();
      try {
        oldest.gain.gain.cancelScheduledValues(now);
        oldest.gain.gain.setValueAtTime(Math.max(FLOOR, oldest.gain.gain.value), now);
        oldest.gain.gain.exponentialRampToValueAtTime(FLOOR, now + 0.03);
      } catch (e) { /* already finished */ }
    }
    return list;
  }

  /* ------------------------------------------------------------------ *
   * Ducking — a counter, not a flag, so overlapping speech doesn't restore
   * the effects bus early.
   * ------------------------------------------------------------------ */

  var ducks = 0;        // open-ended ducks currently held
  var duckUntil = 0;    // audio time a timed duck runs to

  function ducking() {
    return ducks > 0 || duckUntil > ctx.currentTime;
  }

  /**
   * Rewrite the duck automation from now. Called whenever the duck state
   * changes. Everything is scheduled on the audio clock, so a timed duck
   * releases at an exact sample rather than whenever a setTimeout happens
   * to fire.
   */
  function schedule() {
    var t = ctx.currentTime;
    var pairs = [[sfxBus.gain, cfg.duckTo], [musicBus.gain, cfg.duckMusicTo]];

    for (var i = 0; i < pairs.length; i++) {
      var g = pairs[i][0], depth = pairs[i][1];
      try { g.cancelScheduledValues(t); } catch (e) {}
      g.setValueAtTime(g.value, t);

      if (!ducking()) {
        g.linearRampToValueAtTime(1, t + cfg.duckRelease);
        continue;
      }
      g.linearRampToValueAtTime(depth, t + cfg.duckAttack);

      // An open-ended duck holds until its release() is called, so only a
      // purely timed duck gets a scheduled way back up.
      if (ducks === 0 && duckUntil > t) {
        g.setValueAtTime(depth, Math.max(duckUntil, t + cfg.duckAttack));
        g.linearRampToValueAtTime(1, Math.max(duckUntil, t + cfg.duckAttack) + cfg.duckRelease);
      }
    }
  }

  function duck() {
    ensure();
    ducks++;
    schedule();
    var released = false;
    return function release() {
      if (released) return;
      released = true;
      ducks = Math.max(0, ducks - 1);
      schedule();
    };
  }

  function duckFor(seconds) {
    ensure();
    var end = ctx.currentTime + Math.max(0, seconds);
    if (end > duckUntil) duckUntil = end;
    schedule();
  }

  /* ------------------------------------------------------------------ *
   * Comic timing
   *
   * Comedy is structure, and the rest of this file actively fights it:
   * `vary` randomises every shot, which is right for avoiding fatigue and
   * wrong for a gag. These three give repetition a shape.
   * ------------------------------------------------------------------ */

  var runs = {};   // escalate() state, keyed by sound
  var gags = {};   // gag() state, keyed by setup>punchline

  /**
   * Each call in a run steps up the scale; the run resets after a pause.
   * Rising pitch is how a streak reads as escalation rather than repetition.
   */
  function escalate(name, opts) {
    opts = opts || {};
    var step  = opts.step == null ? 2 : opts.step;          // semitones
    var cap   = opts.cap == null ? 7 : opts.cap;            // steps before it plateaus
    var reset = (opts.resetAfter == null ? 1.8 : opts.resetAfter) * 1000;

    var now = Date.now();
    var r = runs[name];
    if (!r || now - r.at > reset) r = runs[name] = { n: 0, at: now };
    r.at = now;

    var semis = Math.min(r.n, cap) * step;
    r.n++;

    play(name, {
      pitch:  (opts.pitch == null ? 1 : opts.pitch) * Math.pow(2, semis / 12),
      volume: opts.volume,
      vary:   opts.vary == null ? 0.02 : opts.vary,   // tight: the rise is the point
      delay:  opts.delay
    });
    return r.n;
  }

  /**
   * Rule of three. Plays `setup` until the Nth call, which plays `punchline`
   * instead and starts the count again. The joke is that the pattern breaks.
   */
  function gag(setup, punchline, opts) {
    opts = opts || {};
    var every = opts.every == null ? 3 : opts.every;
    var reset = (opts.resetAfter == null ? 5 : opts.resetAfter) * 1000;

    var k = setup + '>' + punchline;
    var now = Date.now();
    var g = gags[k];
    if (!g || now - g.at > reset) g = gags[k] = { n: 0, at: now };
    g.at = now;
    g.n++;

    if (g.n >= every) {
      g.n = 0;
      play(punchline, opts.punch);
      return true;
    }
    play(setup, opts.setup);
    return false;
  }

  /**
   * Schedule a run of cues on the audio clock. Numbers are gaps in seconds.
   *
   *   SFX.sequence(['ratchet', 0.55, 'boing']);
   *   SFX.sequence(['drumroll', 1.1, 'levelUp']);
   *   SFX.sequence([{ sound: 'coin', pitch: 1 }, 0.12, { sound: 'coin', pitch: 1.26 }]);
   *
   * Everything is scheduled up front, so timing is sample-accurate rather
   * than at the mercy of setTimeout — which matters, because a gag that is
   * 40 ms late is not a gag.
   *
   * @returns {number} total length in seconds
   */
  function sequence(items, opts) {
    if (!ensure()) return 0;
    opts = opts || {};
    var t = 0;

    for (var i = 0; i < items.length; i++) {
      var it = items[i];
      if (typeof it === 'number') { t += it; continue; }

      if (typeof it === 'string') {
        play(it, { delay: t, vary: opts.vary, volume: opts.volume });
        continue;
      }
      var o = { delay: t + (it.at || 0) };
      for (var k in it) if (k !== 'sound' && k !== 'at') o[k] = it[k];
      play(it.sound, o);
    }
    return t;
  }

  /* ------------------------------------------------------------------ *
   * Public API
   * ------------------------------------------------------------------ */

  function play(name, opts) {
    if (!ensure() || muted) return;
    var recipe = recipes[name];
    if (!recipe) {
      if (global.console) console.warn('SFX: no sound named "' + name + '"');
      return;
    }
    opts = opts || {};

    // Random pitch on every shot, so a sound fired fifty times in a row
    // never sounds like a stuck record.
    var vary = opts.vary == null ? 0.05 : opts.vary;
    var pitch = (opts.pitch == null ? 1 : opts.pitch) * (1 + (Math.random() * 2 - 1) * vary);

    var trim = opts.trim === false ? 1 : (TRIM[name] == null ? 1 : TRIM[name]);
    var callGain = ctx.createGain();
    callGain.gain.value = (opts.volume == null ? 1 : opts.volume) * trim;
    callGain.connect(sfxBus);

    var dur = DUR[name] == null ? 1 : DUR[name];
    var delay = opts.delay > 0 ? opts.delay : 0;
    var at = ctx.currentTime + 0.001 + delay;
    reserve(name).push({ gain: callGain, until: at + dur + 0.1 });

    var prev = out;
    out = callGain;
    try {
      recipe(at, pitch);
    } finally {
      out = prev;
    }

    setTimeout(function () {
      try { callGain.disconnect(); } catch (e) {}
    }, (delay + dur + 1) * 1000);
  }

  var SFX = {
    play: play,
    list: function () { return Object.keys(recipes); },

    volume: function (v) {
      masterVol = Math.max(0, Math.min(1, v));
      if (master && !muted) master.gain.value = masterVol;
      return masterVol;
    },
    mute: function (v) {
      muted = v == null ? !muted : !!v;
      if (master) master.gain.value = muted ? 0 : masterVol;
      return muted;
    },
    isMuted: function () { return muted; },

    /* --- ducking ---------------------------------------------------- */

    /** Duck effects and music until the returned release() is called. */
    duck: duck,
    /** Duck for an exact span on the audio clock. For a clip of known length. */
    duckFor: duckFor,
    isDucked: function () { return ctx ? ducking() : false; },

    /* --- routing ---------------------------------------------------- */

    /** Effects bus. Ducks under voice. Sampled one-shots belong here. */
    bus: function () { ensure(); return sfxBus; },
    /** Speech bus. Never ducked. Route voice-over here. */
    voiceBus: function () { ensure(); return voiceBus; },
    /** Music bus. Ducks harder than effects. */
    musicBus: function () { ensure(); return musicBus; },
    /** Post-fader, pre-limiter. Only if you know why you want it. */
    masterBus: function () { ensure(); return master; },
    analyser: function () { ensure(); return scope; },

    /* --- state ------------------------------------------------------ */

    /** Serialise for persistence; sfx.js does no storage of its own. */
    state: function () { return { volume: masterVol, muted: muted }; },
    restore: function (s) {
      if (!s) return;
      if (typeof s.volume === 'number') SFX.volume(s.volume);
      if (typeof s.muted === 'boolean') SFX.mute(s.muted);
    },

    /** Tune the mix. Safe at any time — the output chain is rewired live. */
    configure: function (o) {
      var touchesOutput = false;
      for (var k in o) {
        if (!(k in cfg)) continue;
        if (cfg[k] !== o[k] && (k === 'limiter' || k === 'clipKnee')) touchesOutput = true;
        cfg[k] = o[k];
      }
      if (ctx && touchesOutput) wireOutput();
      return cfg;
    },

    /* --- musical key ------------------------------------------------ */

    /**
     * Quantise sustained notes to a scale, so cues sit in your music rather
     * than against it. `SFX.key(null)` turns it off.
     *
     *   SFX.key('C pentatonic')   // nothing can clash. Best default.
     *   SFX.key('D minor');
     *
     * @returns {string|null} the key in force
     */
    key: setKey,
    keys: function () { return Object.keys(SCALES); },
    /** Nearest in-key frequency. Exposed for your own recipes. */
    snap: snap,

    /* --- comic timing ----------------------------------------------- */

    escalate: escalate,
    gag: gag,
    sequence: sequence,

    /* --- extension -------------------------------------------------- */

    define: function (name, fn, meta) {
      recipes[name] = fn;
      if (meta && meta.trim != null) TRIM[name] = meta.trim;
      if (meta && meta.duration != null) DUR[name] = meta.duration;
      SFX[name] = function (o) { play(name, o); };
    },
    /** Read or override a measured trim. */
    trim: function (name, value) {
      if (value != null) TRIM[name] = value;
      return TRIM[name] == null ? 1 : TRIM[name];
    },
    unlock: ensure,
    _blip: blip, _hiss: hiss, _wobbler: wobbler,
    get context() { return ctx; }
  };

  Object.keys(recipes).forEach(function (name) {
    SFX[name] = function (opts) { play(name, opts); };
  });

  /* ------------------------------------------------------------------ *
   * Lifecycle
   * ------------------------------------------------------------------ */

  // Browsers keep audio suspended until a real user gesture.
  var events = ['pointerdown', 'keydown', 'touchstart'];
  function unlock() {
    ensure();
    if (ctx && ctx.state === 'running') {
      events.forEach(function (e) { global.removeEventListener(e, unlock, true); });
    }
  }
  events.forEach(function (e) {
    if (global.addEventListener) {
      global.addEventListener(e, unlock, { capture: true, passive: true });
    }
  });

  // Tablets suspend the context when the app backgrounds and do not reliably
  // resume it on return. Without this, audio dies silently after the first
  // home-button press — the kind of bug you only find on a real device.
  if (global.document && global.document.addEventListener) {
    global.document.addEventListener('visibilitychange', function () {
      if (!ctx) return;
      if (global.document.hidden) {
        if (ctx.suspend) ctx.suspend();
      } else {
        if (ctx.resume) ctx.resume();
        // A duck left open when the app backgrounded would never release.
        if (ducks > 0 || duckUntil > 0) {
          ducks = 0; duckUntil = 0;
          glide(sfxBus.gain, 1, 0.05);
          glide(musicBus.gain, 1, 0.05);
        }
      }
    });
  }

  global.SFX = SFX;
  if (typeof module !== 'undefined' && module.exports) module.exports = SFX;

})(typeof window !== 'undefined' ? window : this);
